window.db=window.supabase.createClient('https://noqcqvomcugduhuwrboc.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcWNxdm9tY3VnZHVodXdyYm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5ODMxNDAsImV4cCI6MjEwMDU1OTE0MH0.G2mVt8YemX97iEjDXkNwjDzjswJgaf2O7gyVyQ5BBHU');
window.money=n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(n);window.escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
window.applyRecurring=async uid=>{const today=new Date(),date=today.toISOString().slice(0,10);const{data:list}=await db.from('recurring_transactions').select('*').lte('day_of_month',today.getDate());if(!list?.length)return;const{data:done}=await db.from('transactions').select('description').eq('date',date).like('description','🔁 %');const names=new Set((done||[]).map(x=>x.description));const rows=list.filter(x=>!names.has(`🔁 ${x.description}`)).map(x=>({user_id:uid,type:x.type,description:`🔁 ${x.description}`,amount:x.amount,category:x.category,date}));if(rows.length)await db.from('transactions').insert(rows)};
window.requireUser=async()=>{const{data:{session}}=await db.auth.getSession();if(!session){location.replace('login.html');return null}await applyRecurring(session.user.id);return session.user};window.signOut=async()=>{await db.auth.signOut();location.replace('login.html')};
window.setupTheme=()=>{const current=localStorage.getItem('mmTheme');document.body.classList.toggle('dark',current==='dark');const button=document.getElementById('themeToggle');if(button){button.innerHTML=current==='dark'?'<i class="bi bi-sun"></i> สว่าง':'<i class="bi bi-moon-stars"></i> มืด';button.onclick=()=>{const dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);localStorage.setItem('mmTheme',dark?'dark':'light');setupTheme()}}};
const nativeBridge=document.createElement('script');nativeBridge.src='js/native-bridge.js';nativeBridge.async=false;nativeBridge.onload=()=>window.mintMindNative?.setup?.();document.head.append(nativeBridge);
document.querySelectorAll('main > .nav-pills').forEach(nav=>{if(!nav.querySelector('[href="ai-center.html"]'))nav.insertAdjacentHTML('beforeend','<li><a class="nav-link" href="ai-center.html"><i class="bi bi-stars"></i> AI Center</a></li>');if(!nav.querySelector('[href="profile.html"]'))nav.insertAdjacentHTML('beforeend','<li><a class="nav-link" href="profile.html"><i class="bi bi-person-circle"></i> โปรไฟล์</a></li>')});
const pageKinds=[['transactionForm','transactions-page'],['budgetForm','planner-page'],['profileForm','profile-page'],['reminderForm','reminders-page'],['liabilityForm','liabilities-page'],['chatForm','ai-page']];pageKinds.forEach(([id,className])=>{if(document.getElementById(id))document.body.classList.add(className)});
document.querySelectorAll('label:not([for])').forEach(label=>{const control=label.querySelector('input,select,textarea')||label.parentElement?.querySelector('input,select,textarea');if(control?.id)label.htmlFor=control.id});
if(document.body.classList.contains('planner-page')){const labels={budgetCategory:'หมวดหมู่',budgetLimit:'งบสูงสุดต่อเดือน',goalTitle:'ชื่อเป้าหมาย',goalTarget:'จำนวนเงินเป้าหมาย',goalSaved:'ออมแล้ว',recurringType:'ประเภทรายการ',recurringDescription:'รายละเอียด',recurringAmount:'จำนวนเงิน',recurringCategory:'หมวดหมู่',recurringDay:'วันที่ทำรายการ'};for(const[id,text]of Object.entries(labels)){const control=document.getElementById(id);if(!control||document.querySelector(`label[for="${id}"]`))continue;const label=document.createElement('label');label.className='form-label';label.htmlFor=id;label.textContent=text;control.before(label)}}
if(document.body.classList.contains('ai-page'))document.getElementById('chatInput')?.setAttribute('aria-label','ถาม AI เกี่ยวกับการเงิน');
const activePageLink=document.querySelector('main > .nav-pills .nav-link.active');activePageLink?.setAttribute('aria-current','page');
const pageHeading={
  'planner-page':['วางแผนการเงิน','ตั้งงบประมาณและติดตามเป้าหมายออมของคุณ','bi-bullseye'],
  'reminders-page':['เตือนความจำ','จัดการกำหนดชำระและเรื่องสำคัญ ไม่ให้พลาดวันนัด','bi-bell'],
  'ai-page':['AI ผู้ช่วยการเงิน','ถามเรื่องรายรับ–รายจ่ายได้ด้วยโหมดฟรีในแอป','bi-stars']
};
for(const [className,[title,subtitle,icon]] of Object.entries(pageHeading)){if(!document.body.classList.contains(className))continue;const heading=document.createElement('section');heading.className='secondary-page-heading';heading.innerHTML=`<span class="secondary-page-heading-icon"><i class="bi ${icon}"></i></span><div><small>MINTMIND · MONEY SPACE</small><h1>${title}</h1><p>${subtitle}</p></div>`;document.querySelector('main > .nav-pills')?.after(heading);break}
if(['planner-page','reminders-page','ai-page'].some(className=>document.body.classList.contains(className)))document.querySelectorAll('main > .row h1').forEach(oldHeading=>{const heading=document.createElement('h2');heading.className=oldHeading.className;heading.innerHTML=oldHeading.innerHTML;oldHeading.replaceWith(heading)});
if(!location.pathname.endsWith('/reminders.html'))document.querySelectorAll('main > .nav-pills a[href="reminders.html"]').forEach(link=>link.closest('li')?.remove());
document.querySelectorAll('.btn').forEach(button=>button.classList.add('glass-btn'));
if(document.getElementById('receiptFile')){const checker=document.createElement('script');checker.src='js/receipt-checker.js';document.head.append(checker)}
const categoryField=document.getElementById('category');if(categoryField?.tagName==='INPUT'){const categorySelect=document.createElement('select');categorySelect.id='category';categorySelect.className=categoryField.className;['อาหาร','เดินทาง','ช้อปปิ้ง','บิล/ที่อยู่อาศัย','สุขภาพ','บันเทิง','เงินเดือน','การศึกษา','อื่น ๆ'].forEach(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;categorySelect.append(option)});categoryField.replaceWith(categorySelect)}
if(document.getElementById('reminderDate')&&!document.getElementById('repeatMonthly')){const wrap=document.createElement('label');wrap.className='form-check mt-3';wrap.innerHTML='<input id="repeatMonthly" class="form-check-input" type="checkbox"><span class="form-check-label">เตือนซ้ำทุกเดือน</span>';reminderDate.after(wrap)}
if(location.pathname.endsWith('/profile.html')){const profileForm=document.getElementById('profileForm');if(profileForm&&!document.querySelector('[href="change-password.html"]'))profileForm.insertAdjacentHTML('afterend','<hr class="my-4"><a class="btn btn-outline-secondary" href="change-password.html"><i class="bi bi-shield-lock me-1"></i>เปลี่ยนรหัสผ่าน</a>')}
window.suggestCategory=text=>{const t=String(text).toLowerCase();const rules=[['อาหาร',/กาแฟ|ข้าว|อาหาร|ร้านอาหาร|7-11|เซเว่น|grab food|ชา|เบเกอรี่/],['เดินทาง',/bts|mrt|taxi|แท็กซี่|grab|น้ำมัน|รถเมล์|ทางด่วน|parking/],['บิล/ที่อยู่อาศัย',/ค่าไฟ|ค่าน้ำ|ค่าเน็ต|อินเทอร์เน็ต|ค่าเช่า|โทรศัพท์|มือถือ/],['สุขภาพ',/ยา|หมอ|คลินิก|โรงพยาบาล|ฟิตเนส/],['บันเทิง',/หนัง|เกม|netflix|spotify|คอนเสิร์ต/],['การศึกษา',/หนังสือ|คอร์ส|เรียน|ค่าเทอม/],['เงินเดือน',/เงินเดือน|salary|โบนัส/]];return rules.find(([,pattern])=>pattern.test(t))?.[0]||'อื่น ๆ'};
if(document.getElementById('incomeTotal')){const insights=document.createElement('script');insights.src='js/free-ai.js';document.head.append(insights)}
if(document.getElementById('description')&&document.getElementById('category')){const autoCategory=document.createElement('script');autoCategory.src='js/auto-category.js';document.head.append(autoCategory)}
if(document.getElementById('goalList')){const goalAi=document.createElement('script');goalAi.src='js/goal-ai.js';document.head.append(goalAi)}
if(document.getElementById('goalList')){const goalHistory=document.createElement('script');goalHistory.src='js/goal-history.js';document.head.append(goalHistory)}
if(document.getElementById('incomeTotal')){const onboarding=document.createElement('script');onboarding.src='js/onboarding.js';document.head.append(onboarding)}
const motionStyles=document.createElement('link');motionStyles.rel='stylesheet';motionStyles.href='css/motion.css';document.head.append(motionStyles);
const extraStyles=document.createElement('link');extraStyles.rel='stylesheet';extraStyles.href='css/features.css';document.head.append(extraStyles);
const uxStyles=document.createElement('link');uxStyles.rel='stylesheet';uxStyles.href='css/ux.css';document.head.append(uxStyles);const uxScript=document.createElement('script');uxScript.src='js/ux-enhancements.js';document.head.append(uxScript);
const shellStyles=document.createElement('link');shellStyles.rel='stylesheet';shellStyles.href='css/app-shell.css';document.head.append(shellStyles);const shellScript=document.createElement('script');shellScript.src='js/app-shell.js';document.head.append(shellScript);
const chartStyles=document.createElement('link');chartStyles.rel='stylesheet';chartStyles.href='css/chart-tuning.css';document.head.append(chartStyles);
const bankingStyles=document.createElement('link');bankingStyles.rel='stylesheet';bankingStyles.href='css/banking-ui.css';document.head.append(bankingStyles);if(document.getElementById('balanceTotal')){const bankingScript=document.createElement('script');bankingScript.src='js/banking-ui.js';document.head.append(bankingScript)}
if(document.getElementById('balanceTotal')){const debtReminderStyles=document.createElement('link');debtReminderStyles.rel='stylesheet';debtReminderStyles.href='css/debt-reminder.css';document.head.append(debtReminderStyles)}
const ocrStyles=document.createElement('link');ocrStyles.rel='stylesheet';ocrStyles.href='css/ocr-ui.css';document.head.append(ocrStyles);
const threeDStyles=document.createElement('link');threeDStyles.rel='stylesheet';threeDStyles.href='css/three-d.css';document.head.append(threeDStyles);const threeDScript=document.createElement('script');threeDScript.src='js/three-d.js';document.head.append(threeDScript);
const navStyles=document.createElement('link');navStyles.rel='stylesheet';navStyles.href='css/nav-polish.css';document.head.append(navStyles);
const mobileStyles=document.createElement('link');mobileStyles.rel='stylesheet';mobileStyles.href='css/mobile-app.css';document.head.append(mobileStyles);
const bubbleStyles=document.createElement('link');bubbleStyles.rel='stylesheet';bubbleStyles.href='css/bubble-ui.css';document.head.append(bubbleStyles);
const bubbleScript=document.createElement('script');bubbleScript.src='js/bubble-ui.js';bubbleScript.defer=true;document.body.append(bubbleScript);
const secondaryStyles=document.createElement('link');secondaryStyles.rel='stylesheet';secondaryStyles.href='css/secondary-pages.css';document.head.append(secondaryStyles);
const appExperienceStyles=document.createElement('link');appExperienceStyles.rel='stylesheet';appExperienceStyles.href='css/app-experience.css?v=20261005-1';document.head.append(appExperienceStyles);
const appExperienceScript=document.createElement('script');appExperienceScript.src='js/app-experience.js?v=20261005-1';document.head.append(appExperienceScript);

