let liabilityUserId,liabilities=[],editingLiabilityId=null;
const debtNumber=value=>Number(value||0);
const debtToast=(message,color='success')=>{const toast=document.createElement('div');toast.className=`toast text-bg-${color} border-0`;toast.innerHTML=`<div class="d-flex"><div class="toast-body">${message}</div><button class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div>`;toasts.append(toast);new bootstrap.Toast(toast).show()};
const resetLiabilityForm=()=>{editingLiabilityId=null;liabilityForm.reset();liabilitySubmit.textContent='บันทึกหนี้สิน';cancelLiabilityEdit.classList.add('d-none')};
const renderLiabilities=()=>{const total=liabilities.reduce((sum,item)=>sum+debtNumber(item.outstanding_balance),0),monthly=liabilities.reduce((sum,item)=>sum+debtNumber(item.monthly_payment),0);totalDebt.textContent=money(total);monthlyDebt.textContent=money(monthly);liabilityCount.textContent=`${liabilities.length} รายการ`;liabilityRows.innerHTML=liabilities.map(item=>`<tr><td><b>${escapeHtml(item.name)}</b><small class="d-block text-secondary">${escapeHtml(item.source||'')}</small></td><td>${escapeHtml(item.liability_type)}</td><td>${item.due_date?new Date(`${item.due_date}T00:00:00`).toLocaleDateString('th-TH'):'—'}</td><td class="text-end fw-semibold text-danger">${money(item.outstanding_balance)}</td><td class="text-end">${item.monthly_payment===null?'—':money(item.monthly_payment)}</td><td class="text-end text-nowrap"><button class="btn btn-sm text-primary" data-action="edit" data-id="${item.id}"><i class="bi bi-pencil"></i></button><button class="btn btn-sm text-danger" data-action="delete" data-id="${item.id}"><i class="bi bi-trash"></i></button></td></tr>`).join('')||'<tr><td colspan="6" class="text-center empty py-5">ยังไม่มีหนี้สินที่บันทึกไว้</td></tr>'};
const loadLiabilities=async()=>{const {data,error}=await db.from('liabilities').select('*').order('updated_at',{ascending:false});if(error)return debtToast('กรุณารัน Supabase schema เวอร์ชันล่าสุดก่อน','danger');liabilities=data||[];renderLiabilities();window.mintMindNative?.scheduleDebtNotifications?.(liabilities).catch(()=>{})};
liabilityForm.onsubmit=async event=>{event.preventDefault();liabilitySubmit.disabled=true;const row={user_id:liabilityUserId,name:liabilityName.value.trim(),liability_type:liabilityType.value,outstanding_balance:debtNumber(liabilityBalance.value),monthly_payment:liabilityPayment.value===''?null:debtNumber(liabilityPayment.value),due_date:liabilityDue.value||null,source:liabilitySource.value.trim()||null,updated_at:new Date().toISOString()};const {error}=editingLiabilityId?await db.from('liabilities').update(row).eq('id',editingLiabilityId):await db.from('liabilities').insert(row);if(error)debtToast(error.message,'danger');else{debtToast(editingLiabilityId?'อัปเดตหนี้สินแล้ว':'เพิ่มหนี้สินแล้ว');resetLiabilityForm();loadLiabilities()}liabilitySubmit.disabled=false};
liabilityRows.onclick=async event=>{const button=event.target.closest('button');if(!button)return;const item=liabilities.find(value=>value.id===button.dataset.id);if(!item)return;if(button.dataset.action==='delete'){if(!confirm(`ลบ ${item.name} หรือไม่?`))return;const {error}=await db.from('liabilities').delete().eq('id',item.id);if(error)return debtToast(error.message,'danger');debtToast('ลบหนี้สินแล้ว');loadLiabilities();return}editingLiabilityId=item.id;liabilityName.value=item.name;liabilityType.value=item.liability_type;liabilityBalance.value=item.outstanding_balance;liabilityPayment.value=item.monthly_payment??'';liabilityDue.value=item.due_date||'';liabilitySource.value=item.source||'';liabilitySubmit.textContent='บันทึกการแก้ไข';cancelLiabilityEdit.classList.remove('d-none');window.scrollTo({top:0,behavior:'smooth'})};
cancelLiabilityEdit.onclick=resetLiabilityForm;logoutBtn.onclick=signOut;(async()=>{setupTheme();const user=await requireUser();if(!user)return;liabilityUserId=user.id;resetLiabilityForm();loadLiabilities();setTimeout(()=>{if(!window.mintMindNative?.isNative?.()||document.getElementById('nativeDebtNotifications'))return;const button=document.createElement('button');button.id='nativeDebtNotifications';button.type='button';button.className='btn btn-outline-light btn-sm mt-3';button.innerHTML='<i class="bi bi-bell-fill me-1"></i>เปิดแจ้งเตือนในแอป';document.querySelector('.liability-hero > div')?.append(button);button.onclick=async()=>{const granted=await window.mintMindNative.requestNotifications();if(!granted)return debtToast('กรุณาอนุญาตการแจ้งเตือนในการตั้งค่าแอป','warning');await window.mintMindNative.scheduleDebtNotifications(liabilities);button.innerHTML='<i class="bi bi-check-lg me-1"></i>เปิดแจ้งเตือนแล้ว';button.disabled=true;debtToast('ตั้งการแจ้งเตือนหนี้ในแอปแล้ว')}} ,100)})();
